server:
  port: 8081

  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/social_service_db
      username: postgres
      password: tom4wolf
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    security:
      oauth2:
        resourceserver:
          jwt:
            secret-key: my-super-secret-key-which-matches-auth-service

# Feign service URLs
services:
  post:
    url: http://localhost:8082
  profile:
    url: http://localhost:8083

# Logging
logging:
  level:
    org.springframework: INFO
